version: "3.8"

services:
  whatsapp:
    build:
      context: ./wpp
      dockerfile: Dockerfile
    container_name: whatsapp-bot
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
    volumes:
      - ./wpp/sessions:/app/.wwebjs_auth  # Persistência das sessões do WhatsApp
    working_dir: /app

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: tcc_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: java_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - whatsapp
      - db
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    working_dir: /app
