server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,mappings"

camel:
  servlet:
    mapping:
      context-path: /api/*
  main:
    jmx-enabled: false

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.apache.camel.impl.engine.AbstractCamelContext: INFO
    org.apache.camel.impl.engine.DefaultRouteStartupOrder: INFO
